import logging
import os
import re
from datetime import datetime
from integrations import LLMRouter

logger = logging.getLogger(__name__)

PRD_TEMPLATE_PATH = os.path.join(os.path.dirname(__file__), "..", "templates", "prd_template.md")

PRD_SYSTEM = """You are a senior product manager converting meeting transcripts into structured PRDs.
Be specific, actionable, and concise. Use the provided template structure exactly."""

PRD_PROMPT = """Convert this meeting transcript into a Product Requirements Document (PRD).

Meeting Transcript:
{transcript}

Client: {client_name}
Date: {date}

Follow this structure exactly:
1. Executive Summary (2-3 sentences)
2. Problem Statement (what pain they have)
3. Proposed Solution (what we discussed)
4. Key Features (bullet list, 3-7 items)
5. Success Metrics (measurable KPIs)
6. Timeline & Milestones (rough phases)
7. Open Questions / Next Steps

Be specific to what was discussed. Do not add features not mentioned."""

PROTOTYPE_PROMPT = """Based on this PRD excerpt, generate a minimal HTML prototype description.

PRD Summary: {prd_summary}

Describe (in plain text) 2-3 key UI screens needed for a quick mockup:
- Screen name
- Main elements (3-5 bullet points each)
- Primary CTA button

Keep it concise — this feeds into a lightweight HTML stub generator."""

HTML_STUB_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} — Prototype</title>
    <style>
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
                background: #f5f5f5; color: #333; }}
        .header {{ background: #2563eb; color: white; padding: 16px 24px;
                   font-size: 18px; font-weight: 600; }}
        .container {{ max-width: 960px; margin: 32px auto; padding: 0 24px; }}
        .card {{ background: white; border-radius: 8px; padding: 24px;
                 margin-bottom: 24px; box-shadow: 0 1px 3px rgba(0,0,0,.1); }}
        h2 {{ font-size: 16px; font-weight: 600; margin-bottom: 12px; color: #1e40af; }}
        p {{ font-size: 14px; line-height: 1.6; color: #555; margin-bottom: 8px; }}
        .btn {{ display: inline-block; background: #2563eb; color: white;
                padding: 10px 20px; border-radius: 6px; font-size: 14px;
                font-weight: 500; cursor: pointer; border: none; margin-top: 12px; }}
        .tag {{ display: inline-block; background: #dbeafe; color: #1e40af;
                padding: 2px 8px; border-radius: 4px; font-size: 12px; margin: 2px; }}
        ul {{ padding-left: 20px; font-size: 14px; color: #555; line-height: 1.8; }}
    </style>
</head>
<body>
    <div class="header">{title} — Prototype</div>
    <div class="container">
        {content}
        <div class="card" style="background:#f0fdf4;border:1px solid #bbf7d0;">
            <h2>Generated by BD Automation</h2>
            <p>This is a lightweight prototype stub. Replace placeholder content with real designs.</p>
            <p><strong>Generated:</strong> {date}</p>
        </div>
    </div>
</body>
</html>"""


class PRDGeneratorAgent:
    def __init__(self):
        self.llm = LLMRouter()
        self.template = self._load_template()

    def _load_template(self) -> str:
        try:
            with open(PRD_TEMPLATE_PATH) as f:
                return f.read()
        except Exception:
            return ""

    def generate_prd(self, transcript: str, client_name: str = "Client") -> str:
        """Convert a meeting transcript into a full PRD."""
        if not transcript or len(transcript.strip()) < 50:
            raise ValueError("Transcript too short to generate PRD")

        prompt = PRD_PROMPT.format(
            transcript=transcript[:8000],
            client_name=client_name,
            date=datetime.utcnow().strftime("%B %d, %Y"),
        )

        prd = self.llm.complete(prompt, system=PRD_SYSTEM, max_tokens=1500, temperature=0.4)
        logger.info(f"PRD generated for {client_name}: {len(prd)} chars")
        return prd

    def generate_prototype_html(self, prd: str, title: str = "Product Prototype") -> str:
        """Generate a lightweight HTML stub from a PRD."""
        # Extract first 1000 chars as summary
        prd_summary = prd[:1000]

        prompt = PROTOTYPE_PROMPT.format(prd_summary=prd_summary)
        description = self.llm.complete(prompt, max_tokens=600, temperature=0.5)

        # Convert description to HTML cards
        content = self._description_to_html(description, prd)

        return HTML_STUB_TEMPLATE.format(
            title=title,
            content=content,
            date=datetime.utcnow().strftime("%Y-%m-%d"),
        )

    def _description_to_html(self, description: str, prd: str) -> str:
        # Extract key features from PRD for display
        features = []
        for line in prd.split("\n"):
            line = line.strip()
            if line.startswith(("- ", "• ", "* ")) and len(line) > 10:
                features.append(line.lstrip("-•* ").strip())

        features_html = ""
        if features:
            items = "".join(f"<li>{f}</li>" for f in features[:8])
            features_html = f"""
        <div class="card">
            <h2>Key Features</h2>
            <ul>{items}</ul>
        </div>"""

        # Overview card
        first_para = prd.split("\n\n")[0] if prd else description[:300]
        overview = re.sub(r"#.*\n", "", first_para).strip()[:400]

        return f"""
        <div class="card">
            <h2>Product Overview</h2>
            <p>{overview}</p>
            <button class="btn">Book Demo</button>
        </div>
        {features_html}
        <div class="card">
            <h2>Prototype Notes</h2>
            <p>{description[:500]}</p>
        </div>"""

    def transcribe_audio(self, audio_path: str) -> str:
        """Transcribe audio using local Whisper (fallback: AssemblyAI)."""
        try:
            import whisper
            model = whisper.load_model("base")
            result = model.transcribe(audio_path)
            return result["text"]
        except ImportError:
            logger.warning("Whisper not installed — trying AssemblyAI")
            return self._transcribe_assemblyai(audio_path)

    def _transcribe_assemblyai(self, audio_path: str) -> str:
        import os
        import requests
        import time

        api_key = os.getenv("ASSEMBLYAI_API_KEY", "")
        if not api_key:
            raise ValueError("Neither whisper nor ASSEMBLYAI_API_KEY available")

        headers = {"authorization": api_key, "content-type": "application/json"}

        with open(audio_path, "rb") as f:
            upload_resp = requests.post(
                "https://api.assemblyai.com/v2/upload",
                headers={"authorization": api_key},
                data=f,
            )
        audio_url = upload_resp.json()["upload_url"]

        transcript_resp = requests.post(
            "https://api.assemblyai.com/v2/transcript",
            json={"audio_url": audio_url},
            headers=headers,
        )
        transcript_id = transcript_resp.json()["id"]

        for _ in range(60):
            time.sleep(5)
            poll = requests.get(
                f"https://api.assemblyai.com/v2/transcript/{transcript_id}",
                headers=headers,
            )
            status = poll.json()["status"]
            if status == "completed":
                return poll.json()["text"]
            if status == "error":
                raise RuntimeError(f"AssemblyAI error: {poll.json().get('error')}")

        raise TimeoutError("AssemblyAI transcription timed out")
